umbrella.index:
    path: /
    controller: Torr\Umbrella\Controller\UmbrellaController::index

umbrella.component:
    path: /{category}/{key}
    controller: Torr\Umbrella\Controller\UmbrellaController::component
    requirements:
        category: '[a-z0-9][a-z0-9-_]*'
        key: '[a-z0-9][a-z0-9-_]*'

umbrella.preview:
    path: /_c/{category}/{key}
    controller: Torr\Umbrella\Controller\UmbrellaController::preview
    requirements:
        category: '[a-z0-9][a-z0-9-_]*'
        key: '[a-z0-9][a-z0-9-_]*'

umbrella.docs:
    path: /_d/{key}
    controller: Torr\Umbrella\Controller\UmbrellaController::globalDocs
    requirements:
        key: '[a-z0-9][a-z0-9-_]*'

umbrella.page:
    path: /_p/{key}
    controller: Torr\Umbrella\Controller\UmbrellaController::customPage
    requirements:
        key: '[a-z0-9][a-z0-9-_]*'
