services:
    _defaults:
        autoconfigure: true
        autowire: true

    Torr\Umbrella\:
        resource: ../src/*
        exclude: ../src/{Data,Exception,UmbrellaBundle.php}

    Torr\Umbrella\Component\Library\ComponentLibraryLoader:
        $templatesDir: '%kernel.project_dir%/templates'
        $subDir: !abstract 'configuration value: umbrella.templates_directory'

    Torr\Umbrella\Controller\UmbrellaController:
        bind:
            $profiler: '@?profiler'

    Torr\Umbrella\Config\UmbrellaConfig:
        $enabledInProduction: !abstract 'configuration value: umbrella.enabled_in_production'

    Torr\Umbrella\Paths\UmbrellaPaths:
        $templatesPath: '%kernel.project_dir%/templates'
