services:
    _defaults:
        autoconfigure: true
        autowire: true

    Torr\Umbrella\:
        resource: ../src/*
        exclude: ../src/{Data,Exception,UmbrellaBundle.php}

    Torr\Umbrella\Controller\UmbrellaController:
        bind:
            $profiler: '@?profiler'

    Torr\Umbrella\Config\UmbrellaConfig:
        $enabledInProduction: !abstract 'configuration value: umbrella.enabled_in_production'

    Torr\Umbrella\Paths\UmbrellaPaths:
        $templatesPath: '%kernel.project_dir%/templates'
        $layoutsDir: !abstract 'configuration value: umbrella.templates_directory'
        $docsDir: !abstract 'configuration value: umbrella.docs_directory'

    Torr\Umbrella\Cache\ProductionCache:
        $isDebug: '%kernel.debug%'

    Torr\Umbrella\Section\CustomPagesRegistry:
        $pages: !tagged_locator { tag: umbrella.custom-page, default_index_method: getKey }
